# vim:fileencoding=utf-8:foldmethod=marker

# : Manager {{{

[manager]
cwd = { fg = "#179299" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "#df8e1d", bold = true, italic = true, underline = true }
find_position = { fg = "#ea76cb", bg = "reset", bold = true, italic = true }

# Marker
marker_copied   = { fg = "#40a02b", bg = "#40a02b" }
marker_cut      = { fg = "#d20f39", bg = "#d20f39" }
marker_marked   = { fg = "#df8e1d", bg = "#df8e1d" }
marker_selected = { fg = "#1e66f5", bg = "#1e66f5" }

# Tab
tab_active   = { fg = "#eff1f5", bg = "#4c4f69" }
tab_inactive = { fg = "#4c4f69", bg = "#bcc0cc" }
tab_width    = 1

# Count
count_copied   = { fg = "#eff1f5", bg = "#40a02b" }
count_cut      = { fg = "#eff1f5", bg = "#d20f39" }
count_selected = { fg = "#eff1f5", bg = "#1e66f5" }

# Border
border_symbol = "│"
border_style  = { fg = "#8c8fa1" }

# Highlighting
syntect_theme = "~/.config/yazi/Catppuccin-latte.tmTheme"

# : }}}


# : Status {{{

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#bcc0cc", bg = "#bcc0cc" }

# Mode
mode_normal = { fg = "#eff1f5", bg = "#1e66f5", bold = true }
mode_select = { fg = "#eff1f5", bg = "#40a02b", bold = true }
mode_unset  = { fg = "#eff1f5", bg = "#dd7878", bold = true }

# Progress
progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#1e66f5", bg = "#bcc0cc" }
progress_error  = { fg = "#d20f39", bg = "#bcc0cc" }

# Permissions
permissions_t = { fg = "#1e66f5" }
permissions_r = { fg = "#df8e1d" }
permissions_w = { fg = "#d20f39" }
permissions_x = { fg = "#40a02b" }
permissions_s = { fg = "#8c8fa1" }

# : }}}


# : Input {{{

[input]
border   = { fg = "#1e66f5" }
title    = {}
value    = {}
selected = { reversed = true }

# : }}}


# : Select {{{

[select]
border   = { fg = "#1e66f5" }
active   = { fg = "#ea76cb" }
inactive = {}

# : }}}


# : Tasks {{{

[tasks]
border  = { fg = "#1e66f5" }
title   = {}
hovered = { underline = true }

# : }}}


# : Which {{{

[which]
mask            = { bg = "#ccd0da" }
cand            = { fg = "#179299" }
rest            = { fg = "#7c7f93" }
desc            = { fg = "#ea76cb" }
separator       = "  "
separator_style = { fg = "#acb0be" }

# : }}}


# : Help {{{

[help]
on      = { fg = "#ea76cb" }
exec    = { fg = "#179299" }
desc    = { fg = "#7c7f93" }
hovered = { bg = "#acb0be", bold = true }
footer  = { fg = "#bcc0cc", bg = "#4c4f69" }

# : }}}


# : File-specific styles {{{

[filetype]

rules = [
	# Images
	{ mime = "image/*", fg = "#179299" },

	# Videos
	{ mime = "video/*", fg = "#df8e1d" },
	{ mime = "audio/*", fg = "#df8e1d" },

	# Archives
	{ mime = "application/zip",             fg = "#ea76cb" },
	{ mime = "application/gzip",            fg = "#ea76cb" },
	{ mime = "application/x-tar",           fg = "#ea76cb" },
	{ mime = "application/x-bzip",          fg = "#ea76cb" },
	{ mime = "application/x-bzip2",         fg = "#ea76cb" },
	{ mime = "application/x-7z-compressed", fg = "#ea76cb" },
	{ mime = "application/x-rar",           fg = "#ea76cb" },

	# Fallback
	{ name = "*", fg = "#4c4f69" },
	{ name = "*/", fg = "#1e66f5" }
]

# : }}}
